name: ayuprep
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  apple_sign_in_safety: ^0.0.6
  assets_audio_player: ^3.0.3+6
  cached_network_image: ^3.0.0
  cloud_firestore: ^3.1.4
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.3
  http: any
  facebook_audience_network: ^1.0.0-nullsafety.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.6.0
  firebase_messaging: ^11.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_exif_rotation: ^0.4.1
  flutter_html: ^3.0.0-alpha.1
  flutter_local_notifications: ^9.1.5
  flutter_localizations:
    sdk: flutter
  flutter_login_facebook: ^1.2.0
  flutter_svg: ^1.0.0
  google_fonts: ^2.1.0
  google_mobile_ads: ^1.0.1
  google_sign_in: ^5.1.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  image_picker: ^0.8.0+1
  in_app_purchase: ^2.0.0
  internet_connection_checker: ^0.0.1+2
  device_info_plus: ^3.2.1

  ios_insecure_screen_detector: ^0.0.2
  intl: ^0.17.0
  intl_phone_field: ^2.1.0
  jaguar_jwt: ^3.0.0
  just_audio: ^0.9.12
  launch_review: ^3.0.1
  lottie: ^1.1.0
  octo_image: ^1.0.0+1
  #otp_autofill: ^1.1.0
  package_info_plus: ^1.0.6
  path_provider: ^2.0.2
  pin_code_fields: ^7.3.0
  scratcher: ^2.1.0
  screenshot: ^1.2.1
  share_plus: ^3.0.4
  shared_preferences: ^2.0.6
  sms_autofill: ^2.2.0
  url_launcher: ^6.0.12
  wakelock: ^0.5.6
  webview_flutter: ^3.0.0
  country_code_picker: ^2.0.2
  flutter_windowmanager: ^0.2.0
  encrypt:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/images/profile/

    - assets/images/emojis/
    - assets/images/coins/

    - assets/languages/
    - assets/animations/

    - assets/sounds/
    - assets/files/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
